name: Minify JavaScript

on:
  push:
    branches:
      - main
      - develop

jobs:
  minify-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install minify
      run: npm install minify -g

    - name: Minify JavaScript
      run: minify main.js > main.min.js

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit minified file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Minify JavaScript"
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
